global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 5.0
  width: 10.0
  height: 20.0
  resolution: 0.05
  origin_x: -5.0
  origin_y: -5.0
  static_map: true
  rolling_window: false
